// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#include "SetRecord.h"  // my header
#include "translation.h"

namespace System { namespace Cxns {


::cppns::SetRecord SetRecord::toCpp() {
    return ::cppns::SetRecord(
        transform<std::unordered_set<std::string>, Windows::Foundation::Collections::IIterable<Platform::String^>^>()(Set),
        transform<std::unordered_set<int32_t>, Windows::Foundation::Collections::IIterable<int32_t>^>()(Iset));
}

SetRecord^ SetRecord::fromCpp(const ::cppns::SetRecord& value) {
    SetRecord^ ret = ref new SetRecord();
    ret->Set = transform<std::unordered_set<std::string>, Windows::Foundation::Collections::IIterable<Platform::String^>^>()(value.set);
    ret->Iset = transform<std::unordered_set<int32_t>, Windows::Foundation::Collections::IIterable<int32_t>^>()(value.iset);
    return ret;
}

} }  // namespace System::Cxns
