// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#pragma once

#include "../cpp/set_record.hpp"

namespace System { namespace Cxns {

public ref class SetRecord sealed : public Platform::Object {
    property Windows::Foundation::Collections::IIterable<Platform::String^>^ Set;
    property Windows::Foundation::Collections::IIterable<int32_t>^ Iset;
internal:
    ::cppns::SetRecord toCpp();
    static SetRecord^ fromCpp(const ::cppns::SetRecord& value);
};

} }  // namespace System::Cxns
