// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "Translation.h"  // my header
#include "../../../../support-lib/cx/translate.cpp"

namespace System { namespace Cxns {


} }  // namespace System::Cxns
