// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include <cstdint>
#include "optional\optional.hpp"
#include <string>
#include <utility>

namespace cppns {

struct ClientReturnedRecord final {
    int64_t record_id;
    std::string content;
    std::experimental::optional<std::string> misc;

    ClientReturnedRecord(int64_t record_id,
                         std::string content,
                         std::experimental::optional<std::string> misc)
    : record_id(std::move(record_id))
    , content(std::move(content))
    , misc(std::move(misc))
    {}
};

}  // namespace cppns
