// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include <functional>

namespace cppns {

enum class Color : int {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    /**
     * "It is customary to list indigo as a color lying between blue and violet, but it has
     * never seemed to me that indigo is worth the dignity of being considered a separate
     * color. To my eyes it seems merely deep blue." --Isaac Asimov
     */
    INDIGO,
    VIOLET
};

}  // namespace cppns

namespace std {

template <>
struct hash<::cppns::Color> {
    size_t operator()(::cppns::Color type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
