// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 
#pragma once

namespace System {
	public ref class BoolRef sealed
	{
	public:
		property bool Value;
		BoolRef(bool value) { Value = value; }
	};
	public ref class ByteRef sealed
	{
	public:
		property unsigned char Value;
		ByteRef(unsigned char value) { Value = value; }
	};
	public ref class ShortRef sealed
	{
	public:
		property short Value;
		ShortRef(short value) { Value = value; }
	};
	public ref class IntRef sealed
	{
	public:
		property int Value;
		IntRef(int value) { Value = value; }
	};
	public ref class LongRef sealed
	{
	public:
		property long long Value;
		LongRef(long long value) { Value = value; }
	};
	public ref class FloatRef sealed
	{
	public:
		property float Value;
		FloatRef(float value) { Value = value; }
	};
	public ref class DoubleRef sealed
	{
	public:
		property double Value;
		DoubleRef(double value) { Value = value; }
	};

	public ref class StringRef sealed
	{
	public:
		property Platform::String^ Value;
		StringRef(Platform::String^ value) { Value = value; }
	};
}