// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

import java.util.HashMap;

public final class MapRecord {


    /*package*/ final HashMap<String, Long> map;

    /*package*/ final HashMap<Integer, Integer> imap;

    public MapRecord(
            HashMap<String, Long> map,
            HashMap<Integer, Integer> imap) {
        this.map = map;
        this.imap = imap;
    }

    public HashMap<String, Long> getMap() {
        return map;
    }

    public HashMap<Integer, Integer> getImap() {
        return imap;
    }
}
