// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

import java.util.ArrayList;
import java.util.HashSet;

public final class NestedCollection {


    /*package*/ final ArrayList<HashSet<String>> setList;

    public NestedCollection(
            ArrayList<HashSet<String>> setList) {
        this.setList = setList;
    }

    public ArrayList<HashSet<String>> getSetList() {
        return setList;
    }
}
