// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

import java.util.ArrayList;

public final class PrimitiveList {


    /*package*/ final ArrayList<Long> list;

    public PrimitiveList(
            ArrayList<Long> list) {
        this.list = list;
    }

    public ArrayList<Long> getList() {
        return list;
    }
}
