// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

public final class RecordWithNestedDerivings implements Comparable<RecordWithNestedDerivings> {


    /*package*/ final int key;

    /*package*/ final RecordWithDerivings rec;

    public RecordWithNestedDerivings(
            int key,
            RecordWithDerivings rec) {
        this.key = key;
        this.rec = rec;
    }

    public int getKey() {
        return key;
    }

    public RecordWithDerivings getRec() {
        return rec;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof RecordWithNestedDerivings)) {
            return false;
        }
        RecordWithNestedDerivings other = (RecordWithNestedDerivings) obj;
        return this.key == other.key &&
                this.rec.equals(other.rec);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + key;
        hashCode = hashCode * 31 + rec.hashCode();
        return hashCode;
    }

    @Override
    public int compareTo(RecordWithNestedDerivings other)  {
        int tempResult;
        if (this.key < other.key) {
            tempResult = -1;
        } else if (this.key > other.key) {
            tempResult = 1;
        } else {
            tempResult = 0;
        }
        if (tempResult != 0) {
            return tempResult;
        }
        tempResult = this.rec.compareTo(other.rec);
        if (tempResult != 0) {
            return tempResult;
        }
        return 0;
    }
}
