// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

public final class RecordWithDurationAndDerivings implements Comparable<RecordWithDurationAndDerivings> {


    /*package*/ final java.time.Duration dt;

    public RecordWithDurationAndDerivings(
            java.time.Duration dt) {
        this.dt = dt;
    }

    public java.time.Duration getDt() {
        return dt;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof RecordWithDurationAndDerivings)) {
            return false;
        }
        RecordWithDurationAndDerivings other = (RecordWithDurationAndDerivings) obj;
        return this.dt.equals(other.dt);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + (dt.hashCode());
        return hashCode;
    }

    @Override
    public int compareTo(RecordWithDurationAndDerivings other)  {
        int tempResult;
        tempResult = this.dt.compareTo(other.dt);
        if (tempResult != 0) {
            return tempResult;
        }
        return 0;
    }
}
