// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#import "ClientReturnedRecord.h"
#import <Foundation/Foundation.h>


@protocol ClientInterface

/** Returns record of given string */
- (nonnull ClientReturnedRecord *)getRecord:(int64_t)recordId
                                 utf8string:(nonnull NSString *)utf8string
                                       misc:(nullable NSString *)misc;

- (double)identifierCheck:(nonnull NSData *)data
                        r:(int32_t)r
                     jret:(int64_t)jret;

- (nonnull NSString *)returnStr;

@end
