// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import <Foundation/Foundation.h>

extern BOOL const ConstantsInterfaceBoolConstant;
extern int8_t const ConstantsInterfaceI8Constant;
extern int16_t const ConstantsInterfaceI16Constant;
extern int32_t const ConstantsInterfaceI32Constant;
extern int64_t const ConstantsInterfaceI64Constant;
extern float const ConstantsInterfaceF32Constant;
extern double const ConstantsInterfaceF64Constant;

@interface ConstantsInterface : NSObject

- (void)dummy;

@end
