// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "Constants.h"
#import <Foundation/Foundation.h>

@interface Constants : NSObject
- (nonnull instancetype)initWithSomeInteger:(int32_t)someInteger
                                 someString:(nonnull NSString *)someString;
+ (nonnull instancetype)constantsWithSomeInteger:(int32_t)someInteger
                                      someString:(nonnull NSString *)someString;

@property (nonatomic, readonly) int32_t someInteger;

@property (nonatomic, readonly, nonnull) NSString * someString;

@end

extern BOOL const ConstantsBoolConstant;
extern int8_t const ConstantsI8Constant;
extern int16_t const ConstantsI16Constant;
extern int32_t const ConstantsI32Constant;
extern int64_t const ConstantsI64Constant;
extern float const ConstantsF32Constant;
extern double const ConstantsF64Constant;
extern NSString * __nonnull const ConstantsStringConstant;
extern NSNumber * __nullable const ConstantsOptionalIntegerConstant;
extern Constants * __nonnull const ConstantsObjectConstant;
