// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import "EmptyRecord.h"


@implementation EmptyRecord

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)emptyRecord
{
    return [[self alloc] init];
}

@end
