// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "djinni_support.hpp"
#include "empty_record.hpp"

namespace jnins {

class EmptyRecord final {
public:
    using CppType = ::cppns::EmptyRecord;
    using JniType = jobject;

    using Boxed = EmptyRecord;

    ~EmptyRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    EmptyRecord();
    friend ::djinni::JniClass<EmptyRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("EmptyRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace jnins
