// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#pragma once

#include "djinni_support.hpp"
#include "primitive_list.hpp"

namespace jnins {

class PrimitiveList final {
public:
    using CppType = ::cppns::PrimitiveList;
    using JniType = jobject;

    using Boxed = PrimitiveList;

    ~PrimitiveList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    PrimitiveList();
    friend ::djinni::JniClass<PrimitiveList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("PrimitiveList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_list { ::djinni::jniGetFieldID(clazz.get(), "list", "Ljava/util/ArrayList;") };
};

}  // namespace jnins
