// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#include "record_with_duration_and_derivings.hpp"  // my header
#include "Duration-jni.hpp"
#include "Marshal.hpp"

namespace jnins {

RecordWithDurationAndDerivings::RecordWithDurationAndDerivings() = default;

RecordWithDurationAndDerivings::~RecordWithDurationAndDerivings() = default;

auto RecordWithDurationAndDerivings::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<RecordWithDurationAndDerivings>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Duration<::djinni::F64, ::djinni::Duration_ns>::fromCpp(jniEnv, c.dt)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto RecordWithDurationAndDerivings::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<RecordWithDurationAndDerivings>::get();
    return {::djinni::Duration<::djinni::F64, ::djinni::Duration_ns>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_dt))};
}

}  // namespace jnins
