// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_helpers.hpp"

namespace jnins {

class TestHelpers final : ::djinni::JniInterface<::cppns::TestHelpers, TestHelpers> {
public:
    using CppType = std::shared_ptr<::cppns::TestHelpers>;
    using JniType = jobject;

    using Boxed = TestHelpers;

    ~TestHelpers();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<TestHelpers>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<TestHelpers>::get()._toJava(jniEnv, c)}; }

private:
    TestHelpers();
    friend ::djinni::JniClass<TestHelpers>;
    friend ::djinni::JniInterface<::cppns::TestHelpers, TestHelpers>;

};

}  // namespace jnins
