// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_duration.hpp"

namespace jnins {

class TestDuration final : ::djinni::JniInterface<::cppns::TestDuration, TestDuration> {
public:
    using CppType = std::shared_ptr<::cppns::TestDuration>;
    using JniType = jobject;

    using Boxed = TestDuration;

    ~TestDuration();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<TestDuration>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<TestDuration>::get()._toJava(jniEnv, c)}; }

private:
    TestDuration();
    friend ::djinni::JniClass<TestDuration>;
    friend ::djinni::JniInterface<::cppns::TestDuration, TestDuration>;

};

}  // namespace jnins
